version: 1.0

env:
  DEFAULT_ENV_VAR: default var
  OVERRIDE_ENV_VAR_0: old e0
  OVERRIDE_ENV_VAR_1: old e1

.cargo-build: &cargo-build
  - cargo build $CARGO_ARGS

chains:
  test:
    matrix:
      - env:
          OVERRIDE_ENV_VAR_0: new e0
    tasks:
      - env:
          OVERRIDE_ENV_VAR_1: new e1
        run:
          - printf "$DEFAULT_ENV_VAR"
          - printf "$OVERRIDE_ENV_VAR_0"
          - printf "$OVERRIDE_ENV_VAR_1"
          - |
            echo "+ some"
            echo "+ multiline"
            echo "+ command"
          - printf "{{ args.test }}" # this will require an argument to be passed via '-a args.test="some-argument"'
          - unknown-command
          - printf "too far!"

  "app/cli":
    matrix:
      - workdir: ./code/apps/cli
        env:
          CARGO_ARGS: ""
      - workdir: ./code/apps/cli
        env:
          CARGO_ARGS: "--release"
    tasks:
      - env: {}
        run: *cargo-build
