version: 0.2

chains:
  publish:
    workdir: ./code/app/cli
    pre:
      - build
    tasks:
      - script: |
          sed 's/version = "0.0.0"/version = "'{{ version }}'"/g' Cargo.toml > Cargo.toml.tmp
          mv Cargo.toml.tmp Cargo.toml
          cargo publish --allow-dirty

  build:
    workdir: ./code/app/cli
    matrix:
      - env:
          CARGO_ARGS: ""
      - env:
          CARGO_ARGS: "--release"
    tasks:
      - script: cargo build $CARGO_ARGS
