version: 1.0.0

.cargo-build: &cargo-build
  - cargo build $CARGO_ARGS

chains:
  "app/cli":
    matrix:
      - workdir: ./code/apps/cli
        env:
          CARGO_ARGS: ""
      - workdir: ./code/apps/cli
        env:
          CARGO_ARGS: "--release"
    tasks:
      - run: *cargo-build
