version: "0.0"

nodes:
  build:
    matrix:
      dense:
        dimensions:
          - - env: {}
            - env:
                RELEASE: --release
          - - env: {}
            - env:
                F_JSON: --features format+json
          - - env: {}
            - env:
                F_TOML: --features format+toml
          - - env: {}
            - env:
                F_RON: --features format+ron
    tasks:
      - script: |
          set -e
          export CARGO_FLAGS="$F_JSON $F_TOML $F_RON $RELEASE"
          echo cargo flags: \"$CARGO_FLAGS\"
          cargo build $CARGO_FLAGS

  test:
    tasks:
      - script: |
          cargo test --no-fail-fast

  hook:pre-push:
    pre:
      - build
      - test
    tasks: []
