version: 1.0

chains:
  publish:
    matrix:
      - workdir: ./code/app/cli
    tasks:
      - run:
          - cargo build --release
      - run:
          - sed 's/version = "0.0.0"/version = "'{{ version }}'"/g' Cargo.toml > Cargo.toml.tmp
          - mv Cargo.toml.tmp Cargo.toml
          - cargo publish --allow-dirty

  build:
    matrix:
      - workdir: ./code/app/cli
        env:
          CARGO_ARGS: ""
      - workdir: ./code/app/cli
        env:
          CARGO_ARGS: "--release"
    tasks:
      - run:
          - cargo build $CARGO_ARGS
