name: wiki
on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  website:
    name: website
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: install rust
        run: "curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y"
      - name: install
        run: |
          cargo install mdbook book-summary fmerge
      - name: render manual
        run: |
          # render manpages
          cargo run --target=x86_64-unknown-linux-gnu -- man -o ./markdown -f markdown

          # render and include schema
          cargo run --target=x86_64-unknown-linux-gnu -- config schema > ./docs/schema.json
          fmerge merge -p "<-- %f -->" -f ./docs/README.md > ./docs/README_MERGED.md
          mv ./docs/README_MERGED.md ./docs/README.md

          # include reference
          cat ./markdown/neomake.md >> ./docs/wiki/src/reference.md

          # write index
          cat ./docs/README.md >> ./docs/wiki/src/index.md

          # build book
          cd ./docs/wiki
          book-summary -yms
          mdbook build
      - name: deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/wiki/book
